[package]
name = "bas"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
memchr = "2.7"
anyhow = "1.0"
memmap2 = { version = "=0.9.7",   default-features = false }
brik = { git = "https://github.com/rakivo/brik", rev = "74bc472" }
libc = { version = "0.2.175", optional = true } # madvise
num-traits = "0.2.19"

[features]
default = ["madvise", "brik-fancy-diagnostics"]

madvise = ["libc"]
brik-fancy-diagnostics = ["brik/fancy-diagnostics"]

[profile.release]
opt-level = 3
panic = "abort"
codegen-units = 1
lto = "thin"
debug = false
strip = true

[profile.release-small]
inherits = "release"
opt-level = "z"
panic = "abort"
strip = true
lto = true
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = 1
lto = false
codegen-units = 16
overflow-checks = false

